---
- hosts: host
  name: Nginx configuration
  vars_files:
    - variables/ssh.yaml
    - variables/certificate.yaml
  become: true
  become_method: su

  tasks:

    - name: Copy config file to sites-available area
      template:
        src: site.conf
        dest: "/etc/nginx/sites-available/{{ primary_domain }}"

    - name: Enable site
      file:
        state: link
        src: "/etc/nginx/sites-available/{{ primary_domain }}"
        dest: "/etc/nginx/sites-enabled/{{ primary_domain }}"
      notify:
        - restart nginx

    - name: delete default site
      file:
        state: absent
        path: "/etc/nginx/sites-enabled/default"

    - name: Add stream block to proxy requests by sni
      blockinfile:
        insertafter: EOF
        path: "/etc/nginx/nginx.conf"
        block: '
          stream {
              map $ssl_preread_server_name $sni {
                default nginx;
                {{ sub_domain }} trojan;
              }

              upstream trojan {
                server 127.0.0.1:6443;
              }

              upstream nginx {
                server 127.0.0.1:8443;
              }

              server {
                listen 443;
                listen [::]:443;
                proxy_pass $sni;
                ssl_preread on;
             }
          }
          '
  handlers:
    - name: restart nginx
      become: true
      service:
        name: nginx
        state: restarted
